version: '3'

services:
  ruby:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
      - bundle-volume:/usr/local/bundle
    environment:
      DB_HOST: postgres
      DB_USER: pg
      DB_PASSWORD: password
      DB_DATABASE: dev
    command: sleep infinity
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:postgres
  postgres:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pg
      POSTGRES_DB: dev
      POSTGRES_PASSWORD: password
volumes:
  bundle-volume: null
  postgres-volume: null
